Building with Responsive Web design
somoye123/Responsive-Design pull request #1
Opened 2020-06-19 12:26 UTC by somoye123

2020-06-19 13:52 UTC, trekab requested changes
## Changes Required! :recycle: 
Hi @somoye123 and @OlawaleJoseph! You have done a nice job on this project so far! There are a few issues to fix to complete, however. These include:
- [x] __Top 3 articles section:__ 
  - For large screens, the text should be positioned at the bottom part of these sections. Your clone appears to have the text positioned mostly near the top part.
  - For small screens, they have a very short height. Make them a bit taller so that they appear more as they do on the original site.
- [x] In the comments below, I have highlighted the `font-family` rule which you have repeated several times. It is better you refactor this out into a class of its own in order to avoid such repetition. 
 ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
- [x] The brief description for your pull request could use some improvement. Something to keep in mind when writing a good Pull Request summary is: `Your commits tell a story of how you added changes to your project and the pull request summary is the ultimate summary describing briefly what is achieved by all your commits`. Try to keep this in mind on your next pull requests.
- [x] You have done a nice job with the mobile-first approach. :+1: I have noticed that you have added extra(2) break-points though. This is unnecessary. ([Screenshot on mobile-first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/)).
- [x] __[OPTIONAL]__ Your use of the `main` tag could use some improvement. The [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) should be used for the dominant content of the `<body>` of a document. In your case, it is being used to achieve something that could be achieved using a `section` tag.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2020-06-19 13:52 UTC, trekab commented on main.css
> +}
This property shouldn't have 2 values.

2020-06-19 13:52 UTC, trekab commented on main.css
> +}
Font family names containing whitespace should be quoted. e.g "Helvetica Neue".

2020-06-19 13:52 UTC, trekab commented on main.css
> +}
Font family names containing whitespace should be quoted. e.g "Helvetica Neue".

2020-06-19 13:52 UTC, trekab commented on main.css
> +    font-size: 14px;
Font family names containing whitespace should be quoted. e.g "Helvetica Neue".

2020-06-19 13:52 UTC, trekab commented on main.css
> +    font-size: 14px;
Font family names containing whitespace should be quoted. e.g "Helvetica Neue".

2020-06-19 22:19 UTC, BrittanyBlake requested changes
### Status: Changes Required  🏗️ 🔨 
****
### Hello @somoye123 and @OlawaleJoseph 👋   👋 
You are doing a great job with this project! 👍 You are almost done! 💪 Great job applying the feedback you have received from the previous TSE. 🎖️ 🌟 There are just a few small issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The previous TSE requested that you position the text on the bottom in the top 3 articles section. Great job fixing this, however, they now appear to be pushed too far to the bottom. In some cases, they are spilling off of the image. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-20 at 12 12 18 AM](https://user-images.githubusercontent.com/48804258/85183041-b62f3700-b28a-11ea-8b8d-4cae2ed39f46.png)
The original page 👇 
![Screen Shot 2020-06-20 at 12 13 01 AM](https://user-images.githubusercontent.com/48804258/85183080-cf37e800-b28a-11ea-8c29-2896b6bda415.png)

- [ ] The elements in your navigation bar on the medium screen size are not aligned properly. Please compare your clone with the original page and fix this. 
Your clone 👇 
![Screen Shot 2020-06-20 at 12 16 53 AM](https://user-images.githubusercontent.com/48804258/85183246-5a18e280-b28b-11ea-83c3-eba01699c2dc.png)
The original page 👇 
![Screen Shot 2020-06-20 at 12 17 21 AM](https://user-images.githubusercontent.com/48804258/85183273-6ac95880-b28b-11ea-822e-a608ffe8de6a.png)

- [ ] The footer should remain the same in the small screen size. There is no change in the footer in any of the sizes. Please compare your clone with the original page and fix this.
Your clone👇 
![Screen Shot 2020-06-20 at 12 18 55 AM](https://user-images.githubusercontent.com/48804258/85183331-a2d09b80-b28b-11ea-94af-47401e235527.png)
The original page 👇 
![Screen Shot 2020-06-20 at 12 19 21 AM](https://user-images.githubusercontent.com/48804258/85183346-b1b74e00-b28b-11ea-9d82-23d3051af36e.png)







****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-20 13:05 UTC, somoye123 commented
![Screenshot (859)](https://user-images.githubusercontent.com/41391263/85202449-66b52f00-b2bb-11ea-8c22-fbfa70441f79.png)
![WhatsApp Image 2020-06-20 at 06 01 30](https://user-images.githubusercontent.com/41391263/85202488-9cf2ae80-b2bb-11ea-83fc-e7ee64cfb4a5.jpeg)

The first above image is "The Next Web" opened in developer tools in chrome while the next image is "The Next Web" opened in my actual mobile phone

As such am not sure what you mean by "There is no change in the footer in any of the sizes." @BrittanyBlake 

Thanks

2020-06-20 14:34 UTC, tirthajyoti-ghosh approved these changes
# Status: Approved ✔

## Congratulations team 🎉. Impressive project 🙌👏👌.

### Onto the next project 🚀.

Happy coding 👨‍💻

2020-06-20 19:11 UTC, merged